---

- hosts: all
  become: true
  tasks:
  - name: update repository index
    yum:
      update_cache: yes

  - name: install apache2 package
    yum:
      name: httpd
      state: latest
  - name: Reload service httpd, in all cases
    ansible.builtin.systemd:
      name: httpd.service
      state: reloaded
  
